# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenseapproval', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Expenses',
        ),
    ]
