# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenseapproval', '0003_expenses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='employee_Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
